[settings]
experimental = true # Required to use lockfile.
lockfile = true     # DO NOT FORGET TO `touch mise.lock`!

[tools]
neovim = ['latest', '0.9.0']
lua = 'prefix:5.1'
# An opinionated Lua code formatter
'ubi:JohnnyMorganz/stylua' = 'latest'
# A blazing-fast modern Lua linter written in Rust
'ubi:Kampfkarren/selene' = 'latest'
# Universal markup converter
'ubi:jgm/pandoc' = 'latest'

[tasks.'deps/tests/restore']
run = 'nvim -l tests/run.lua --lazy-restore'

[tasks.'deps/tests/update']
run = 'nvim -l tests/run.lua --lazy-update'

[tasks.test]
depends = ['lint', 'test/*']

[tasks.'test/latest']
run = 'nvim -l tests/run.lua --minitest'

[tasks.'test/0.9']
run = 'mise exec neovim@0.9 -- nvim -u tests/shim_nvim-0.9.lua -l tests/run.lua --minitest'

[tasks.lint]
depends = ['lint/*']

[tasks.'lint/stylua']
run = 'stylua --check .'

[tasks.'lint/selene']
run = 'selene .'

[tasks.'generate/panvimdoc']
env.DIR = '.buildcache/panvimdoc'
# shell = 'bash -eo pipefail -c'
run = '''
VER="$(cat .panvimdoc.version)"
test -d $DIR || git clone https://github.com/kdheepak/panvimdoc $DIR
false
git -C $DIR checkout $VER 2>/dev/null || (git -C $DIR fetch && git -C $DIR checkout $VER)
GITHUB_ACTIONS= $DIR/panvimdoc.sh \
    --project-name ruscmd \
    --description 'NORMAL and CMDLINE modes support in Russian keyboard layout' \
    --input-file README.md \
    --shift-heading-level-by -1
'''
